const backend_url = process.env.REACT_APP_ENVIROMENT === 'production' ? process.env.REACT_APP_API_PRODUCTION_URL : process.env.REACT_APP_API_DEVELOPMENT_URL;

export const endpoints = {
    login: `${backend_url}/auth/login`,
    register: `${backend_url}/user/sign-up`,
    socialLogin: `${backend_url}/auth/social-login`,
    sendOtp: `${backend_url}/auth/sendOtp`,
    updateNotification: `${backend_url}/user/notification`,
    verifyOtp: `${backend_url}/auth/verifyOtp`,
    resetPassword: `${backend_url}/auth/forgot-password`,
    changePassword: `${backend_url}/auth/change-password`,
    logout: `${backend_url}/auth/logout`,
    profile: `${backend_url}/user/profile`,
    updateProfile: `${backend_url}/user/profile`,
    deleteAccount: `${backend_url}/user/delete`,
    getTrips: `${backend_url}/trip`,
    dashboardData: `${backend_url}/dashboard/today-trips-expenses`,
    addTrip: `${backend_url}/trip`,
    updateTrip: `${backend_url}/trip`,
    deleteTrip: `${backend_url}/trip`,
    addExpense: `${backend_url}/expense`,
    getExpenses: `${backend_url}/expense`,
    deleteExpenses: `${backend_url}/expense`,
    editExpense: `${backend_url}/expense`,
    addVehicle: `${backend_url}/vehicle`,
    getVehicles: `${backend_url}/vehicle`,
    editVehicle: `${backend_url}/vehicle`,
    deleteVehicle: `${backend_url}/vehicle`,
    getLocations: `${backend_url}/locations`,
    addLocation: `${backend_url}/locations`,
    editLocation: `${backend_url}/locations`,
    deleteLocation: `${backend_url}/locations`,
    addReading: `${backend_url}/odometer`,
    updateReading: `${backend_url}/odometer`,
    deleteReading: `${backend_url}/odometer`,
    getReading: `${backend_url}/odometer`,
    addRate: `${backend_url}/mileage-rate`,
    customRates: `${backend_url}/mileage-rate`,
    updateRate: `${backend_url}/mileage-rate`,
    // getReports: `${backend_url}/reports/list`,
    getReports: `${backend_url}/reports/v2/list`,
    // addReport: `${backend_url}/reports`,
    addReport: `${backend_url}/reports/v2`,
    xlsReport: `${backend_url}/reports/generate/xls`,
    pdfReport: `${backend_url}/reports/v2/generatePdfReportNew`,
    // pdfReport: `${backend_url}/reports/generate`,
    updateReport: `${backend_url}/reports`,
    reportMail: `${backend_url}/reports/send`,
    // deleteReport: `${backend_url}/reports`,
    // reportDetail: `${backend_url}/reports`,
    reportDetail: `${backend_url}/reports/v2/getReportDetails`,
    tripsToReport: `${backend_url}/reports/v2/addTripsToReport`,
    expensesToReport: `${backend_url}/reports/v2/addExpensesToReport`,
    submitReport: `${backend_url}/reports/v2/submitReport`,
    createTeam: `${backend_url}/teams/create`,
    teamsList: `${backend_url}/teams/list`,
    teamsTree: `${backend_url}/teams/team-tree`,
    parentTeams: `${backend_url}/teams/team-dropdown`,
    inviteMembers: `${backend_url}/members/invite`,
    membersList: `${backend_url}/members/list`,
    updateInfo: `${backend_url}/members`,
    memberTrips: `${backend_url}/teams/all-trips`,
    teamMembers: `${backend_url}/teams/members-list-details`,
    memberExpenses: `${backend_url}/teams/trips-expense`,
    memberReports: `${backend_url}/teams/trips/report`,
    memberInfo: `${backend_url}/members/info`,
    teamCategories: `${backend_url}/teams/team-category`,
    addCategory: `${backend_url}/teams/team-category`,
    addPlaces: `${backend_url}/teams/add-team-paces`,
    placesList: `${backend_url}/teams/team-places`,
    rolesList: `${backend_url}/teams/team-roles`,
    updateTeamName: `${backend_url}/teams/update-team-name`,
    getSummary: `${backend_url}/teams/team-summary`,
    onboardingMembers: `${backend_url}/members/getOnboardingMembers`,
    categoriesUploadMultiple: `${backend_url}/teams/upload-category`,
    placesUploadMultiple: `${backend_url}/teams/upload-places`,
    managersList: `${backend_url}/teams/manager-list-details`,
    removeManager: `${backend_url}/teams/remove-manager`,
    content: `${backend_url}/user/content`,
    exports: `${backend_url}/teams/export-files`,
    summaryReport: `${backend_url}/teams/generate-export`,
    memberReport: `${backend_url}/teams/generate-member-export`,
    // subscriptionPlans: `${backend_url}/subscription/offerings`,
    subscriptionPlans: `${backend_url}/subscription/get-subs`,
    upgradePlan: `${backend_url}/subscription/checkout`,
    membersDropdown: `${backend_url}/members/dropdown`,
    subscriptionSuccess: `${backend_url}/subscription`,
    reimbursementList: `${backend_url}/reports/v2/reimbursementList`,
    checkInvitation: `${backend_url}/members/check-invitation`,
    acceptInvitation: `${backend_url}/members/accept-invitation`,
    reimbursementSubmit: `${backend_url}/reports/v2/acceptRejectReport`,
    renameReport: `${backend_url}/reports/v2/renameReport`,
    deleteReport: `${backend_url}/reports/v2/delete`,
    firstLogin: `${backend_url}/auth/first-login`,
    reimbursementGraphData: `${backend_url}/reports/v2/reimbursementHistoryByMonth`,
}

export default backend_url;


